version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: windsor_db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schemas.sql:/docker-entrypoint-initdb.d/01_schemas.sql:ro

  api:
    image: python:3.12-slim
    container_name: windsor_api
    working_dir: /workspace/api
    command: bash -lc "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file: .env
    volumes:
      - ./:/workspace
    depends_on:
      - db
    ports:
      - "8000:8000"

  app:
    image: python:3.12-slim
    container_name: windsor_app
    working_dir: /workspace/app
    command: bash -lc "pip install -r requirements.txt && streamlit run app.py --server.address 0.0.0.0 --server.port 8501"
    env_file: .env
    volumes:
      - ./:/workspace
    depends_on:
      - api
    ports:
      - "8501:8501"

  indexer:
    image: python:3.12-slim
    container_name: windsor_indexer
    working_dir: /workspace/indexer
    command: bash -lc "pip install -r requirements.txt && python indexer.py --watch"
    env_file: .env
    volumes:
      - ./:/workspace
    depends_on:
      - db

volumes:
  db_data:
